name: leafprint
description: A sustainability app to track carbon footprint and earn eco-rewards.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.65.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  confetti: ^0.7.0
  image_picker: ^1.0.4
  dotted_border: ^2.1.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/